# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3c24a66b8a8973fad494e9fb72fa738454591e6cff528804b238f524cebf556dbf624ca2c19d6d8b6c123d4ea48337deb7cc2e337e4560dbebfc621d7f79c83

test:
  secret_key_base: 5faa162c6231104e530ef6e150d0dde7039669ab391292d6e242f0b6de2470a31956d0a0d22f7de2a257b3bc3fc2743c4f6929793c75e60429a88f88fc787c0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
